### ISSUE TITLE
Create automatically the ercole user when ercole-agent-perl is installed on aix

### ISSUE THREAD

**Issue by amreo** [ercole-io/ercole-agent-perl#17]
**Is your feature request related to a problem? Please describe.**
I want to avoid to type a additional command during the installation

**Describe the solution you'd like**
I want that RPM esecute the command `useradd -g dba -d /home/ercole-agent -m -s /bin/bash -c "Ercole agent user" ercole` when it's installed.

**Describe alternatives you've considered**
Execute the command `useradd -g dba -d /home/ercole-agent -m -s /bin/bash -c "Ercole agent user" ercole` manually

**Additional context**
fpm has the option `--after-install`

**Comment by cirelli94** [comment]
Won't do.
