### ISSUE TITLE
[BUG] - wrong period format on ercole agent perl

### ISSUE THREAD

**Issue by raffaelloferrari** [ercole-io/ercole-agent-perl#74]
On agent perl:

File: hostdata.json Status: 500 Cause: {"error":"json: cannot unmarshal string into Go struct field HostDataBE.period of type uint","message":"Internal Server Error","sourceFilename":"/root/project/data-service/controller/hosts.go","lineNumber":77}

hostdata.json contain `"period":"24"` instead of `"period":24`

**Comment by anbrenna** [comment]
Already solved
